project_inprogress = 'in progress'
project_ready = 'ready'
project_creating_time_ranges = 'creating time ranges'
project_calculating_node_metrics = 'calculating node metrics'
project_failed = 'failed'
backend_url = 'http://localhost:3500/'